"""initial schema

Revision ID: f6744f434c28
Revises: 
Create Date: 2026-05-18 09:45:59.208157

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f6744f434c28'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_posts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.Enum('DAY_FORECAST', 'DAY_NUMBER', 'DAY_ENERGY', 'MYSTICAL_WARNING', 'VIRAL', name='post_kind', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'SENT', 'FAILED', name='post_status', native_enum=False, length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('channel_id', sa.String(length=64), nullable=False),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generated_posts'))
    )
    op.create_index('ix_generated_posts_status_scheduled', 'generated_posts', ['status', 'scheduled_for'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('telegram_username', sa.String(length=64), nullable=True),
    sa.Column('telegram_first_name', sa.String(length=128), nullable=True),
    sa.Column('telegram_last_name', sa.String(length=128), nullable=True),
    sa.Column('language_code', sa.String(length=8), nullable=True),
    sa.Column('full_name', sa.String(length=128), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender', native_enum=False, length=16), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_table('compatibility_checks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('user_birth_date', sa.Date(), nullable=False),
    sa.Column('partner_birth_date', sa.Date(), nullable=False),
    sa.Column('emotional_score', sa.SmallInteger(), nullable=False),
    sa.Column('conflict_score', sa.SmallInteger(), nullable=False),
    sa.Column('romance_score', sa.SmallInteger(), nullable=False),
    sa.Column('karmic_score', sa.SmallInteger(), nullable=False),
    sa.Column('interpretation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('conflict_score BETWEEN 0 AND 100', name=op.f('ck_compatibility_checks_conflict_score_range')),
    sa.CheckConstraint('emotional_score BETWEEN 0 AND 100', name=op.f('ck_compatibility_checks_emotional_score_range')),
    sa.CheckConstraint('karmic_score BETWEEN 0 AND 100', name=op.f('ck_compatibility_checks_karmic_score_range')),
    sa.CheckConstraint('romance_score BETWEEN 0 AND 100', name=op.f('ck_compatibility_checks_romance_score_range')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_compatibility_checks_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compatibility_checks'))
    )
    op.create_index('ix_compatibility_checks_user_created', 'compatibility_checks', ['user_id', 'created_at'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('plan', sa.Enum('FREE', 'PREMIUM', 'LIFETIME', name='subscription_plan', native_enum=False, length=16), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'CANCELED', name='subscription_status', native_enum=False, length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_provider', sa.String(length=32), nullable=True),
    sa.Column('payment_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_subscriptions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions'))
    )
    op.create_index('ix_subscriptions_user_status', 'subscriptions', ['user_id', 'status'], unique=False)
    op.create_table('tarot_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('spread_kind', sa.Enum('SINGLE', 'THREE_CARD', name='tarot_spread_kind', native_enum=False, length=16), nullable=False),
    sa.Column('cards', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('interpretation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tarot_history_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tarot_history'))
    )
    op.create_index('ix_tarot_history_user_created', 'tarot_history', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tarot_history_user_created', table_name='tarot_history')
    op.drop_table('tarot_history')
    op.drop_index('ix_subscriptions_user_status', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index('ix_compatibility_checks_user_created', table_name='compatibility_checks')
    op.drop_table('compatibility_checks')
    op.drop_table('users')
    op.drop_index('ix_generated_posts_status_scheduled', table_name='generated_posts')
    op.drop_table('generated_posts')
    # ### end Alembic commands ###
